const rememberMeVocabs = ["souvenir",
    "로그인 상태 유지",
    "save email address",
    "remember me",
    "save email address",
    "save my login",
    "save my username",
    "save my password",
    "save my email",
    "save my email address",
    "save login",
    "manter",
    "mantenha",
    "save password",
    "save user name",
    "save email",
    "save username",
    "save email address",
    "keep me signed in",
    "아이디 저장",
    "Не спрашивать в следующий раз",
    "lembrar",
    "Запомните меня",
    "ricordami",
    "save login",
    "запомнить меня",
    "Запомни меня",
    "rememberme",
    "mantenha-me conectado",
    "保存登录信息",
    "save login",
    "记住我",
    "save login",
    "保存登录信息",
    "下次自动登录",
    "stay signed in",
    "save login",
    "save id",
    "次回からログオンIDの入力を省略する",
    "save username",
    "keep me logged in",
    "メールアドレスを保存する",
    "を保存",
    "아이디저장",
    "manter conectado",
    "记住我"];